In [10]:
import pandas as pd


import models

/Users/sergigomezpalleja/anaconda3/envs/kaggle/lib/python3.6/site-packages/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_9.4.1) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)

In [4]:
path_data = '/Users/sergigomezpalleja/Downloads/'

In [25]:
train = pd.read_csv(path_data + 'raw_data_master.csv')
df2 = pd.read_csv(path_data + 'all_val.csv')

In [22]:
train.loc[train.sales2 == 0.0, 'sales2']= 1.0

In [26]:
#train.loc[train.sales2 == 1.0]

In [28]:
df2.loc[df2.sales2 == 1.0]

Empty DataFrame
Columns: [Cluster, Brand_Group, Country, year, month, sales2, y_hat]
Index: []

In [11]:
df2sum = models.prepare_dataframe_groups(df2)

/Users/sergigomezpalleja/code_sergi/godatathon18/novartis-datathon/models.py:123: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_group1['Brand_Group'] = 'Brand Group 51, 73, 90'
/Users/sergigomezpalleja/code_sergi/godatathon18/novartis-datathon/models.py:124: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_group2['Brand_Group'] = 'Brand Group 96, 97'
/Users/sergigomezpalleja/code_sergi/godatathon18/novartis-datathon/models.py:125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_group3['Brand_Group'] = 'others'
/Users/sergigomezpalleja/code_sergi/godatathon18/novartis-datathon/models.py:126: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_group_all['Brand_Group'] = 'Brand Group ' + df_group_all['Brand_Group'].astype(str)

In [15]:
df2sum

,Cluster,month,year,Brand_Group,sales2,y_hat
0,Cluster 1,1,2017,"Brand Group 51, 73, 90",4296.506639,5642.098338
1,Cluster 1,2,2017,"Brand Group 51, 73, 90",4841.820450,5932.807496
2,Cluster 1,3,2017,"Brand Group 51, 73, 90",4853.640063,5946.489437
3,Cluster 1,4,2017,"Brand Group 51, 73, 90",4665.829785,5899.400598
4,Cluster 1,5,2017,"Brand Group 51, 73, 90",4934.865629,5962.543914
5,Cluster 1,6,2017,"Brand Group 51, 73, 90",5090.071155,6119.474609
6,Cluster 1,7,2017,"Brand Group 51, 73, 90",4542.637278,5803.674966
7,Cluster 1,8,2017,"Brand Group 51, 73, 90",4678.359105,5844.111289
8,Cluster 1,9,2017,"Brand Group 51, 73, 90",4581.448944,5797.784268
9,Cluster 1,10,2017,"Brand Group 51, 73, 90",5732.617051,6480.525990
10,Cluster 1,11,2017,"Brand Group 51, 73, 90",5224.113211,6144.110899
11,Cluster 1,12,2017,"Brand Group 51, 73, 90",4801.616441,5968.465749
12,Cluster 2,1,2017,"Brand Group 51, 73, 90",9896.366552,8419.928024
13,Cluster 2,2,2017,"Brand Group 51, 73, 90",8812.187858,7197.591438
14,Cluster 2,3,2017,"Brand Group 51, 73, 90",10063.989691,8564.916745
15,Cluster 2,4,2017,"Brand Group 51, 73, 90",8893.475372,7197.591438
16,Cluster 2,5,2017,"Brand Group 51, 73, 90",9954.096220,8419.928024
17,Cluster 2,6,2017,"Brand Group 51, 73, 90",9986.844216,8419.928024
18,Cluster 2,7,2017,"Brand Group 51, 73, 90",9582.995418,7328.817269
19,Cluster 2,8,2017,"Brand Group 51, 73, 90",8624.890035,6859.305011
20,Cluster 2,9,2017,"Brand Group 51, 73, 90",9833.718213,8284.373479
21,Cluster 2,10,2017,"Brand Group 51, 73, 90",9936.104238,8383.783094
22,Cluster 2,11,2017,"Brand Group 51, 73, 90",9831.647194,8406.699345
23,Cluster 2,12,2017,"Brand Group 51, 73, 90",9401.004582,8186.020726
24,Cluster 3,1,2017,"Brand Group 51, 73, 90",7476.121421,6268.251956
25,Cluster 3,2,2017,"Brand Group 51, 73, 90",8501.793815,7445.642736
26,Cluster 3,3,2017,"Brand Group 51, 73, 90",9247.231386,7762.809851
27,Cluster 3,4,2017,"Brand Group 51, 73, 90",7703.156930,7406.537640
28,Cluster 3,5,2017,"Brand Group 51, 73, 90",10932.782360,8604.596679
29,Cluster 3,6,2017,"Brand Group 51, 73, 90",8629.032073,7534.180517
...,...,...,...,...,...,...
546,Cluster 10,8,2017,Brand Group 17,10429.338971,7780.059614
547,Cluster 10,8,2017,Brand Group 24,1838.276045,1877.483173
548,Cluster 10,8,2017,Brand Group 30,8399.292474,8116.034155
549,Cluster 10,8,2017,Brand Group 31,23026.326023,18034.200462
550,Cluster 10,8,2017,Brand Group 36,2902.571087,2283.785246
551,Cluster 10,8,2017,Brand Group 41,13754.075257,12660.817614
552,Cluster 10,9,2017,Brand Group 17,11524.886882,8312.990503
553,Cluster 10,9,2017,Brand Group 24,1225.230011,1364.140412
554,Cluster 10,9,2017,Brand Group 30,11069.061995,10014.279319
555,Cluster 10,9,2017,Brand Group 31,18970.092194,16008.709548
556,Cluster 10,9,2017,Brand Group 36,2742.856051,2220.921376
557,Cluster 10,9,2017,Brand Group 41,12375.412512,11573.148865
558,Cluster 10,10,2017,Brand Group 17,11427.840890,8422.745113
559,Cluster 10,10,2017,Brand Group 24,2035.280813,2014.027870
560,Cluster 10,10,2017,Brand Group 30,10468.539980,9395.084648
561,Cluster 10,10,2017,Brand Group 31,19629.258449,16323.041762
562,Cluster 10,10,2017,Brand Group 36,3014.437676,2388.879916
563,Cluster 10,10,2017,Brand Group 41,14258.268951,13208.637770
564,Cluster 10,11,2017,Brand Group 17,12101.511137,8830.808513
565,Cluster 10,11,2017,Brand Group 24,2974.428086,2565.052365
566,Cluster 10,11,2017,Brand Group 30,10970.041788,9702.352654
567,Cluster 10,11,2017,Brand Group 31,20741.684127,16584.039626
568,Cluster 10,11,2017,Brand Group 36,2914.149271,2305.003389
569,Cluster 10,11,2017,Brand Group 41,14317.677072,13332.084038
570,Cluster 10,12,2017,Brand Group 17,12851.709284,9159.080465
571,Cluster 10,12,2017,Brand Group 24,2725.620546,2397.226265
572,Cluster 10,12,2017,Brand Group 30,10825.435568,9437.186785
573,Cluster 10,12,2017,Brand Group 31,21365.152171,16625.869003
574,Cluster 10,12,2017,Brand Group 36,3057.680491,2353.374626
575,Cluster 10,12,2017,Brand Group 41,14628.896150,13486.940523